name: atbeach
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.2"
  flutter: "^3.0.0"

dependencies:
  animate_do: ^2.1.0
  cloud_firestore: ^3.1.17
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  fluttertoast: ^8.0.9
  get: ^4.6.5
  http: ^0.13.4
  salomon_bottom_bar: ^3.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/illustration/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Thin.ttf
